/**
 * AI Agent eCommerce — Plugin Loader (Core)
 * 
 * Usage:
 *   node core/loader.js --plugin ecommerce-storefront
 *   node core/loader.js --plugin ecommerce-storefront --output .cursor/rules
 *   node core/loader.js --list
 *   node core/loader.js --sync (sync all active plugins from agent.config.json)
 */

import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, "..")

// ─── Load Configuration ───────────────────────────────────────────────────────

function loadConfig() {
  const configPath = path.join(ROOT, "agent.config.json")
  if (!fs.existsSync(configPath)) {
    throw new Error("agent.config.json not found. Run from the agent root directory.")
  }
  return JSON.parse(fs.readFileSync(configPath, "utf-8"))
}

// ─── Plugin Registry ──────────────────────────────────────────────────────────

function getAvailablePlugins() {
  const pluginsDir = path.join(ROOT, "plugins")
  return fs.readdirSync(pluginsDir)
    .filter(name => fs.statSync(path.join(pluginsDir, name)).isDirectory())
    .map(name => {
      const manifestPath = path.join(pluginsDir, name, "plugin.json")
      if (!fs.existsSync(manifestPath)) return null
      const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"))
      return { name, path: path.join(pluginsDir, name), manifest }
    })
    .filter(Boolean)
}

// ─── Skill Loader ─────────────────────────────────────────────────────────────

function loadPluginSkills(pluginDir, manifest, options = {}) {
  const skills = []
  const maxSkills = options.maxSkills ?? 10

  const sortedSkills = [...manifest.skills].sort((a, b) => a.priority - b.priority)
  const selectedSkills = sortedSkills.slice(0, maxSkills)

  for (const skill of selectedSkills) {
    const skillPath = path.join(pluginDir, skill.file)
    if (!fs.existsSync(skillPath)) {
      console.warn(`  ⚠ Skill file not found: ${skill.file}`)
      continue
    }
    const content = fs.readFileSync(skillPath, "utf-8")
    skills.push({ id: skill.id, description: skill.description, content })
  }

  return skills
}

// ─── Context Builder ──────────────────────────────────────────────────────────

function buildCursorRuleContent(manifest, skills) {
  const timestamp = new Date().toISOString()
  const header = `---
description: ${manifest.description}
globs: **/*.{ts,tsx,js,jsx}
alwaysApply: true
---

# ${manifest.name} — AI Agent Skills
> Auto-generated by ai-agent-ecom loader | ${timestamp}
> Version: ${manifest.version}

${manifest.modelHints?.systemPromptAppend ?? ""}

---

`
  const skillSections = skills
    .map(skill => `## ${skill.id}\n${skill.content}`)
    .join("\n\n---\n\n")

  return header + skillSections
}

function buildVSCodeInstructionContent(manifest, skills) {
  const timestamp = new Date().toISOString()
  const header = `# ${manifest.name} — AI Agent Skills
> Auto-generated ${timestamp} | v${manifest.version}

${manifest.modelHints?.systemPromptAppend ?? ""}

`
  const skillSections = skills
    .map(skill => `## ${skill.id}\n${skill.content}`)
    .join("\n\n---\n\n")

  return header + skillSections
}

// ─── Output Writers ───────────────────────────────────────────────────────────

function writeCursorRule(content, pluginName, config) {
  const rulesDir = path.join(ROOT, config.editor.cursor.rulesDir)
  fs.mkdirSync(rulesDir, { recursive: true })
  const outputPath = path.join(rulesDir, `${pluginName}.mdc`)
  fs.writeFileSync(outputPath, content, "utf-8")
  return outputPath
}

function writeVSCodeInstruction(content, pluginName, config) {
  const instructionsDir = path.join(ROOT, config.editor.vscode.instructionsDir)
  fs.mkdirSync(instructionsDir, { recursive: true })
  const outputPath = path.join(instructionsDir, `${pluginName}.md`)
  fs.writeFileSync(outputPath, content, "utf-8")
  return outputPath
}

// ─── CLI ──────────────────────────────────────────────────────────────────────

function printHelp() {
  console.log(`
  ai-agent-ecom loader

  Commands:
    --plugin <name>    Load a specific plugin and generate context files
    --list             List all available plugins
    --sync             Sync all active plugins from agent.config.json
    --help             Show this help

  Options:
    --output <dir>     Override output directory for context files
    --verbose          Enable verbose logging

  Examples:
    node core/loader.js --plugin ecommerce-storefront
    node core/loader.js --sync
    node core/loader.js --list
  `)
}

async function loadPlugin(pluginName, config, options = {}) {
  const pluginDir = path.join(ROOT, "plugins", pluginName)
  const manifestPath = path.join(pluginDir, "plugin.json")

  if (!fs.existsSync(pluginDir)) {
    throw new Error(`Plugin '${pluginName}' not found in plugins/`)
  }
  if (!fs.existsSync(manifestPath)) {
    throw new Error(`Missing plugin.json in plugins/${pluginName}/`)
  }

  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"))
  console.log(`\n📦 Loading plugin: ${manifest.name} v${manifest.version}`)

  const skills = loadPluginSkills(pluginDir, manifest, {
    maxSkills: config.settings.maxSkillsPerContext
  })
  console.log(`  ✓ Loaded ${skills.length} skills`)

  // Generate Cursor rules
  const cursorContent = buildCursorRuleContent(manifest, skills)
  const cursorPath = writeCursorRule(cursorContent, pluginName, config)
  console.log(`  ✓ Cursor rule → ${cursorPath}`)

  // Generate VS Code instructions
  const vscodeContent = buildVSCodeInstructionContent(manifest, skills)
  const vscodePath = writeVSCodeInstruction(vscodeContent, pluginName, config)
  console.log(`  ✓ VS Code instruction → ${vscodePath}`)

  return { manifest, skills, cursorPath, vscodePath }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2)

  if (args.includes("--help") || args.length === 0) {
    printHelp()
    return
  }

  const config = loadConfig()

  if (args.includes("--list")) {
    const plugins = getAvailablePlugins()
    console.log("\n📋 Available plugins:\n")
    plugins.forEach(p => {
      const isActive = config.activePlugins.includes(p.name)
      console.log(`  ${isActive ? "✓" : "○"} ${p.name}`)
      console.log(`      ${p.manifest.description}`)
      console.log(`      Skills: ${p.manifest.skills.length} | v${p.manifest.version}\n`)
    })
    return
  }

  if (args.includes("--sync")) {
    console.log(`\n🔄 Syncing ${config.activePlugins.length} active plugin(s)…`)
    for (const pluginName of config.activePlugins) {
      await loadPlugin(pluginName, config)
    }
    console.log("\n✅ Sync complete!")
    return
  }

  const pluginIdx = args.indexOf("--plugin")
  if (pluginIdx !== -1 && args[pluginIdx + 1]) {
    await loadPlugin(args[pluginIdx + 1], config)
    console.log("\n✅ Plugin loaded!")
    return
  }

  console.error("Unknown command. Run --help for usage.")
  process.exit(1)
}

main().catch(err => {
  console.error("\n❌ Error:", err.message)
  process.exit(1)
})
